name: "Build Docs"
on: 
- pull_request
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Sphinx
      run: sudo apt-get update && sudo apt-get install -y python3-sphinx
    - name: Install nox package
      run: pip3 install nox
    - name: Install Sphinx tab/design extension
      run: pip3 install sphinx-inline-tabs sphinx-design
    - name: Install theme
      run: pip3 install furo
    - name: Build Sphinx docs
      run: nox -s docs
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./build/docs
        name: github-pages
    - name: Uninstall Sphinx
      run: sudo dpkg --purge python3-sphinx
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    needs: build
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.0
        with:
          token: ${{ github.token }}
